# Generated by Django 2.1.5 on 2019-03-25 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 12, 46, 265464), verbose_name='date published'),
        ),
    ]
